languageCode = "en"
languageName = "English"
weight = 1
title = "Xianpeng Shen"

[params]
displayName = "English"
isoCode = "en"
rtl = false
dateFormat = "2006-01-02"
description = "Xianpeng Shen's Blog Site, about DevOps, CI/CD and Open Source"
copyright = "Copyright © 2017–2025 Xianpeng Shen. All rights reserved."

[params.author]
name = "Xianpeng Shen"
email = "xianpeng.shen@gmail.com"
image = "img/sxp.jpg"
imageQuality = 96
headline = "Engineer. Builder. Maintainer. | From Code to Infra"
bio = "Engineer. Builder. Maintainer. | From Code to Infra"
links = [
  { email = "mailto:xianpeng.shen@gmail.com" },
  { rss = "index.xml" },
  { github = "https://github.com/shenxianpeng" },
  { linkedin = "https://www.linkedin.com/in/xianpeng-shen/" },
  { medium = "https://medium.com/@xianpeng.shen/"  },
  { dev = "https://dev.to/shenxianpeng"  },
  { youtube = "https://www.youtube.com/@shenxianpeng" },
]
