languageCode = "zh-cn"
languageName = "简体中文"
weight = 1
title = "DevOps 攻城狮"

[params]
displayName = "简体中文"
isoCode = "zh-cn"
rtl = false
dateFormat = "2006-01-02"
description = "沈显鹏的个人网站，分享关于 DevOps，CI/CD，Build 以及开源。"
copyright = "Copyright © 2017–2025 Xianpeng Shen. All rights reserved."

[params.author]
name = "沈显鹏"
email = "xianpeng.shen@gmail.com"
image = "img/sxp.jpg"
imageQuality = 96
headline = "Engineer. Builder. Maintainer. | From Code to Infra"
bio = "Engineer. Builder. Maintainer. | From Code to Infra"
links = [
  { email = "mailto:xianpeng.shen@gmail.com" },
  { rss = "index.xml" },
  { github = "https://github.com/shenxianpeng" },
  { linkedin = "https://www.linkedin.com/in/xianpeng-shen/" },
  { medium = "https://medium.com/@xianpeng.shen/"  },
  { dev = "https://dev.to/shenxianpeng"  },
  { youtube = "https://www.youtube.com/@shenxianpeng" },
]
