# Header
menu:
  Home: /
  Archives: /archives
  Daily: /daily/
  About: /about
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- recent_posts
# - tag
- tagcloud
- archive

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# disqus
disqus_shortname: shenxianpeng

# Google Analytics
google_analytics: UA-168820225-1
